# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김승기
title: Java & Spring 백엔드 개발자
email: skkim0832@naver.com
website: https://kimseungki94.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  kimseungki94
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring / JavaScript & VueJS 기반의 2년차 백엔드 개발자로 자동결제 서비스 API 개발 및 페이지 개발 등을 해왔습니다.<br>
  항상 <mark>유지보수</mark>와 <mark>가독성</mark>이 높은 코드를 작성하는 개발자가 되기 위해 노력합니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 효성FMS
        link: https://www.hyosungfms.com/
        # link_text: boringcompany.com
        sub_title: 풀스택 개발자
        caption: 2021.01 - 현재
        quote: >
          효성그룹 전자금융 계열사로 CMS서비스를 운영하는 기업
        description: | # this will include new lines to allow paragraphs
            - 사내 프로젝트 개발 및 효성CMS 차세대프로젝트 참여
            - Spring Boot, VueJS, Oracle 환경에서 개발 경험
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SSAFY
        caption: 2021.01 - 2021.12
        sub_title: 3기 교육생 참여
        quote: >
          삼성전자 주관 소프트웨어 개발자 양성 교육
        description: | # this will include new lines to allow paragraphs
          - 개발자로 실무적 역량 습득을 위해 참여
          - 교육생들과 웹 기반 다수 프로젝트 개발 경험

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
